<?php
add_action( 'acf/include_fields', function () {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
		'key' => 'group_67866da26574b',
		'title' => 'Content',
		'fields' => array(
			array(
				'key' => 'field_67866da27eff0',
				'label' => 'Header',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_67866db87eff1',
				'label' => 'Footer',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_67866e067eff2',
				'label' => 'Kontakt',
				'name' => 'contact',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 0,
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_678770589bd6e',
				'label' => 'Termine',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_678770629bd6f',
				'label' => 'Platzhalter Bild',
				'name' => 'platzhalter_bild_termine',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'uploader' => '',
				'return_format' => 'array',
				'library' => 'all',
				'acfe_thumbnail' => 0,
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'allow_in_bindings' => 0,
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_678770bcb6d83',
				'label' => 'Datum (Icon)',
				'name' => 'date_icon',
				'aria-label' => '',
				'type' => 'icon_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'tabs' => array(
					0 => 'dashicons',
					1 => 'media_library',
					2 => 'url',
				),
				'return_format' => 'string',
				'allow_in_bindings' => 0,
				'library' => 'all',
				'default_value' => array(
					'type' => NULL,
					'value' => NULL,
				),
			),
			array(
				'key' => 'field_678770f6b6d84',
				'label' => 'Uhrzeit (Icon)',
				'name' => 'time_icon',
				'aria-label' => '',
				'type' => 'icon_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'tabs' => array(
					0 => 'dashicons',
					1 => 'media_library',
					2 => 'url',
				),
				'return_format' => 'string',
				'allow_in_bindings' => 0,
				'library' => 'all',
				'default_value' => array(
					'type' => NULL,
					'value' => NULL,
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'theme-settings',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

	acf_add_local_field_group( array(
		'key' => 'group_6799ff5989381',
		'title' => 'Startseite',
		'fields' => array(
			array(
				'key' => 'field_679a2ab2fbf94',
				'label' => 'Grußwort',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_679a2accfbf95',
				'label' => 'Portrait',
				'name' => 'portrait',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'allow_in_bindings' => 0,
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_679a2ae3fbf96',
				'label' => 'Grußwort',
				'name' => 'gruswort',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 0,
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_6799ff7c1ed30',
				'label' => 'Daten & Fakten',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_679a01638a51d',
				'label' => 'Koordinaten',
				'name' => 'koordinaten',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_6799ff5a1ed2f',
				'label' => 'Einwohner',
				'name' => 'einwohner',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 800,
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_679a00131ed31',
				'label' => 'Postleitzahl',
				'name' => 'plz',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 54321,
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_679a00251ed32',
				'label' => 'Höhe',
				'name' => 'hohe',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 500,
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_679a00341ed33',
				'label' => 'Fläche',
				'name' => 'flache',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '25,6',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_679a00551ed35',
				'label' => 'Einwohner pro Ortsteil',
				'name' => 'einwohner_ort',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Eintrag hinzufügen',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_679a00761ed36',
						'label' => 'Ortsteil',
						'name' => 'ortsteil',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_679a00551ed35',
					),
					array(
						'key' => 'field_679a007e1ed37',
						'label' => 'Einwohner',
						'name' => 'einwohner',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_679a00551ed35',
					),
				),
			),
			array(
				'key' => 'field_679a00981ed39',
				'label' => 'Personen',
				'name' => 'personen',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 0,
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_679a2b1aa385f',
				'label' => 'Galerie',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_679a2b30a3860',
				'label' => 'linkes Bild',
				'name' => 'linkes_bild',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'allow_in_bindings' => 0,
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_679a2b38a3861',
				'label' => 'rechtes Bild',
				'name' => 'rechtes_bild',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'allow_in_bindings' => 0,
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_679a2b54a3862',
				'label' => 'Geschichte',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_679a2b81a3863',
				'label' => 'Geschichte der Gemeinde',
				'name' => 'geschichte_der_gemeinde',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 0,
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_679a2ba0a3864',
				'label' => 'Sidebar Geschichte',
				'name' => 'sidebar_geschichte',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 0,
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'theme-settings',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

	acf_add_local_field_group( array(
		'key' => 'group_613778ee7083a',
		'title' => 'Termin',
		'fields' => array(
			array(
				'key' => 'field_61377a065c7b4',
				'label' => 'Veranstaltung',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_613778f75c7a5',
				'label' => 'Verein / Organisation / Firma',
				'name' => 'verein',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_613779525c7ab',
				'label' => 'Startdatum',
				'name' => 'startdatum',
				'aria-label' => '',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'd.m.Y',
				'return_format' => 'Ymd',
				'first_day' => 1,
			),
			array(
				'key' => 'field_6137798f5c7ad',
				'label' => 'Uhrzeit',
				'name' => 'uhrzeit',
				'aria-label' => '',
				'type' => 'time_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_6137792e5c7aa',
							'operator' => '!=',
							'value' => 'Ja',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'H:i',
				'return_format' => 'H:i',
			),
			array(
				'key' => 'field_6137792e5c7aa',
				'label' => 'Mehrtägige Veranstaltung',
				'name' => 'more_days',
				'aria-label' => '',
				'type' => 'checkbox',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'Ja' => 'Ja',
				),
				'allow_custom' => 0,
				'default_value' => array(
				),
				'layout' => 'vertical',
				'toggle' => 0,
				'return_format' => 'value',
				'save_custom' => 0,
				'custom_choice_button_text' => 'Eine neue Auswahlmöglichkeit hinzufügen',
			),
			array(
				'key' => 'field_613779785c7ac',
				'label' => 'Enddatum',
				'name' => 'enddatum',
				'aria-label' => '',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_6137792e5c7aa',
							'operator' => '==',
							'value' => 'Ja',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'd.m.Y',
				'return_format' => 'Ymd',
				'first_day' => 1,
			),
			array(
				'key' => 'field_61377a175c7b5',
				'label' => 'Veranstaltungs-Beschreibung',
				'name' => 'beschreibung',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_613779c15c7ae',
				'label' => 'Veranstaltungsort',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_613779d05c7af',
				'label' => 'PLZ',
				'name' => 'plz',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_613779d55c7b0',
				'label' => 'Ort',
				'name' => 'ort',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_613779db5c7b1',
				'label' => 'Straße',
				'name' => 'strasse',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_613779e25c7b2',
				'label' => 'Hausnummer',
				'name' => 'hausnummer',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_613779ef5c7b3',
				'label' => 'Ansprechpartner',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_6137790b5c7a6',
				'label' => 'Vor- Nachname',
				'name' => 'vor-_nachname',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_613779175c7a7',
				'label' => 'Telefonnummer',
				'name' => 'telefonnummer',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_6137791d5c7a8',
				'label' => 'E-Mail Adresse',
				'name' => 'mail',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'termin',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'acfe_display_title' => '',
		'acfe_autosync' => '',
		'acfe_form' => 0,
		'acfe_meta' => '',
		'acfe_note' => '',
	) );

	acf_add_local_field_group( array(
		'key' => 'group_677fdc4888e70',
		'title' => 'Theme Settings',
		'fields' => array(
			array(
				'key' => 'field_678123e456b37',
				'label' => 'Farben',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_678123b456b35',
				'label' => 'Vordergrundfarbe',
				'name' => 'foreground_color',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#000000',
				'enable_opacity' => 0,
				'return_format' => 'string',
				'allow_in_bindings' => 0,
			),
			array(
				'key' => 'field_678123cb56b36',
				'label' => 'Hintergrundfarbe',
				'name' => 'background_color',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#FFFFFF',
				'enable_opacity' => 0,
				'return_format' => 'string',
				'allow_in_bindings' => 0,
			),
			array(
				'key' => 'field_679102c76dcf5',
				'label' => 'Akzentfarbe',
				'name' => 'accent_color',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#404040',
				'enable_opacity' => 0,
				'return_format' => 'string',
				'allow_in_bindings' => 0,
			),
			array(
				'key' => 'field_677fdc48a307d',
				'label' => 'Header',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_67852148b4e68',
				'label' => 'Breite des Header Content',
				'name' => 'inner_header_width',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => 'px',
			),
			array(
				'key' => 'field_677fdc59a307e',
				'label' => 'Logo',
				'name' => 'logo',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'allow_in_bindings' => 0,
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_677fe02a57b6a',
				'label' => 'Logogröße',
				'name' => 'logo_size',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'small' => 'klein',
					'medium' => 'mittel',
					'large' => 'groß',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'allow_in_bindings' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_67863bb2006ea',
				'label' => 'Menü',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_677ff3be109a9',
				'label' => 'Menü auswählen',
				'name' => 'selected_menu',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					2 => 'main-menu',
					3 => 'test',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'allow_in_bindings' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
				'allow_custom' => 0,
				'search_placeholder' => '',
			),
			array(
				'key' => 'field_677fdc8f10d40',
				'label' => 'Footer',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_678524fd9f02a',
				'label' => 'Breite des Footer Content',
				'name' => 'inner_footer_width',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => 'px',
			),
			array(
				'key' => 'field_67851db070a0b',
				'label' => 'Logo',
				'name' => 'logo_footer',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'uploader' => '',
				'return_format' => 'array',
				'library' => 'all',
				'acfe_thumbnail' => 0,
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'allow_in_bindings' => 0,
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_67851db670a0c',
				'label' => 'Logogröße',
				'name' => 'logo_size_footer',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'small' => 'klein',
					'medium' => 'mittel',
					'large' => 'groß',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'allow_in_bindings' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
				'allow_custom' => 0,
				'search_placeholder' => '',
			),
			array(
				'key' => 'field_6784fd0a8ed43',
				'label' => 'Schriften',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_6784fd98f35e0',
				'label' => 'Pixelgröße',
				'name' => '',
				'aria-label' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Bitte geben Sie hier die Schriften in Pixel an z.B. 22',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_67852f0897369',
				'label' => 'Body Text',
				'name' => 'body_text',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 16,
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => 'px',
			),
			array(
				'key' => 'field_6785005079dd6',
				'label' => 'Grundeinstellungen',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_67851e6c0b5cb',
				'label' => 'Breite des Inner Content',
				'name' => 'inner_content_width',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => 'px',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'theme-settings',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

	acf_add_local_field_group( array(
		'key' => 'group_6799dc3e42c67',
		'title' => 'Vereine',
		'fields' => array(
			array(
				'key' => 'field_6799dc3ed6a51',
				'label' => 'Vereinsbild oder Logo',
				'name' => 'association_img',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'allow_in_bindings' => 0,
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_6799dc7fd6a52',
				'label' => 'Kontakt und Adresse',
				'name' => 'contact',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 0,
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_6799dcb5d6a53',
				'label' => 'Webseite',
				'name' => 'website',
				'aria-label' => '',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_6799dcc0d6a54',
				'label' => 'E-Mail',
				'name' => 'e-mail',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'verein',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );
} );








add_action( 'init', function () {

	// REGISTER CPT TERMINE

	register_post_type( 'termin', array(
		'labels' => array(
			'name' => 'Termine',
			'singular_name' => 'Termin',
			'menu_name' => 'Termine',
			'all_items' => 'Alle Termine',
			'edit_item' => 'Termin bearbeiten',
			'view_item' => 'Termin anzeigen',
			'view_items' => 'Termine anzeigen',
			'add_new_item' => 'Neu hinzufügen: Termin',
			'add_new' => 'Neu hinzufügen: Termin',
			'new_item' => 'Neuer Inhaltstyp Termin',
			'parent_item_colon' => 'Termin, übergeordnet:',
			'search_items' => 'Termine suchen',
			'not_found' => 'termine konnten nicht gefunden werden',
			'not_found_in_trash' => 'termine konnten nicht im Papierkorb gefunden werden',
			'archives' => 'Termin-Archive',
			'attributes' => 'Termin-Attribute',
			'insert_into_item' => 'In termin einfügen',
			'uploaded_to_this_item' => 'Zu diesem termin hochgeladen',
			'filter_items_list' => 'termine-Liste filtern',
			'filter_by_date' => 'termine nach Datum filtern',
			'items_list_navigation' => 'Termine-Listen-Navigation',
			'items_list' => 'Termine-Liste',
			'item_published' => 'Termin wurde veröffentlicht.',
			'item_published_privately' => 'Termin wurde privat veröffentlicht.',
			'item_reverted_to_draft' => 'Termin wurde auf Entwurf zurückgesetzt.',
			'item_scheduled' => 'Termin wurde geplant.',
			'item_updated' => 'Termin wurde aktualisiert.',
			'item_link' => 'Termin-Link',
			'item_link_description' => 'Ein Link zu einem Inhaltstyp termin',
		),
		'public' => true,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-calendar-alt',
		'supports' => array(
			0 => 'title',
			1 => 'editor',
			2 => 'thumbnail',
			3 => 'custom-fields',
		),
		'has_archive' => 'termin',
		'rewrite' => array(
			'feeds' => false,
		),
		'delete_with_user' => false,
	) );

	// REGISTER CPT VEREINE

	register_post_type( 'verein', array(
		'labels' => array(
			'name' => 'Vereine',
			'singular_name' => 'Verein',
			'menu_name' => 'Vereine',
			'all_items' => 'Alle Vereine',
			'edit_item' => 'Verein bearbeiten',
			'view_item' => 'Verein anzeigen',
			'view_items' => 'Vereine anzeigen',
			'add_new_item' => 'Neu hinzufügen: Verein',
			'add_new' => 'Neu hinzufügen: Verein',
			'new_item' => 'Neuer Inhaltstyp Verein',
			'parent_item_colon' => 'Verein, übergeordnet:',
			'search_items' => 'Vereine suchen',
			'not_found' => 'Vereine konnten nicht gefunden werden',
			'not_found_in_trash' => 'Vereine konnten nicht im Papierkorb gefunden werden',
			'archives' => 'Vereins-Archive',
			'attributes' => 'Vereins-Attribute',
			'insert_into_item' => 'In Verein einfügen',
			'uploaded_to_this_item' => 'Zu diesem Verein hochgeladen',
			'filter_items_list' => 'Vereine-Liste filtern',
			'filter_by_date' => 'Vereine nach Datum filtern',
			'items_list_navigation' => 'Vereine-Listen-Navigation',
			'items_list' => 'Vereine-Liste',
			'item_published' => 'Verein wurde veröffentlicht.',
			'item_published_privately' => 'Verein wurde privat veröffentlicht.',
			'item_reverted_to_draft' => 'Verein wurde auf Entwurf zurückgesetzt.',
			'item_scheduled' => 'Verein wurde geplant.',
			'item_updated' => 'Verein wurde aktualisiert.',
			'item_link' => 'Verein-Link',
			'item_link_description' => 'Ein Link zu einem Inhaltstyp Verein',
		),
		'public' => true,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-groups',
		'supports' => array(
			0 => 'title',
			1 => 'thumbnail',
			2 => 'custom-fields',
		),
		'has_archive' => 'verein',
		'rewrite' => array(
			'feeds' => false,
		),
		'delete_with_user' => false,
	) );
} );

