name: Deploy WordPress Theme

on:
  push:
    branches:
      - main
      - staging

jobs:
  production-deploy:
    if: github.ref == 'refs/heads/main'
    name: PRODUCTION - Package and Send Theme Zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Prepare Theme for Deployment
        run: |
          mkdir -p build
          rsync -av --exclude=".git" --exclude=".github" --exclude="node_modules" . build/communitytheme-mta
          cd build
          zip -r communitytheme-mta.zip communitytheme-mta

      - name: Upload Zipped Theme to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "build/communitytheme-mta.zip"
          target: "update-server.morethanads.de/packages/"

  staging-deploy:
    if: github.ref == 'refs/heads/staging'
    name: STAGING - Deploy Unzipped Theme
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master


      - name: Prepare Theme for Staging
        run: |
          rm -rf build  # Ensure there's no existing build directory
          mkdir build
          rsync -av --exclude=".git" --exclude=".github" --exclude="node_modules" --exclude="build" . build/

      - name: Install Composer Dependencies
        run: | 
            cd build
            composer install --no-interaction --prefer-dist

      - name: Upload Theme to Staging Server
        uses: burnett01/rsync-deploy-action@v5
        with:
          switches: -av --delete
          path: build/
          remote_path: ct.morethanads.de/wp-content/themes/communitytheme-mta/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

